services:
  - type: web
    name: serenissima-backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/health
    plan: starter